---
# - name: check if flat remix gtk is already installed
#   stat:
#     path: ~/.local/share/themes/Flat-Remix-Blue-Darkest-fullPanel
#   register: flat_remix

- name: clone flat remix gnome
  ansible.builtin.script: "{{ flat_remix_gnome_version }}"
  changed_when: false
  # when: not flat_remix.stat.exists

- name: sync updated flat remix gnome elements
  ansible.posix.synchronize:
    src: "/tmp/flat-remix-gnome/themes/"
    dest: ~/.local/share/themes/
    rsync_opts:
      - "-u"
      - "-a"
      - "--include=Flat-Remix-*"
      - "--include=Flat-Remix-*/**"
      - "--exclude=*"
  delegate_to: "{{ inventory_hostname }}"
  # when: not flat_remix.stat.exists

- name: remove tmp files
  file:
    state: absent
    path: /tmp/flat-remix-gnome
  # when: not flat_remix.stat.exists
