---
- name: install the flat remix snap packages
  become: yes
  community.general.snap:
    name:
      - flat-remix
      - flat-remix-gtk
  changed_when: false
  when: include_snap

- name: apply the snap themes
  ansible.builtin.script: "{{ enable_snaps }}"
  changed_when: false
  when: include_snap
