---
- name: create path wallpaper destination if it does not exist
  file:
    path: "{{ wallpaper_dest }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0770'

- name: copy wallpaper
  ansible.builtin.copy:
    src: "{{ wallpaper_src }}"
    dest: "{{ wallpaper_dest }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0770'

- name: wallpaper
  ansible.builtin.dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: '"{{ wallpaper_dest }}/{{ wallpaper_name }}"'
